local opt = vim.opt
local g = vim.g

opt.clipboard = "unnamedplus"
opt.ttyfast = true
opt.cursorline = true
opt.number = true
opt.autoindent = true
opt.hlsearch = true
opt.incsearch = true
opt.ignorecase = true
opt.showmatch = true
opt.cc = "80"
opt.expandtab = true
opt.tabstop = 2
opt.softtabstop = 2
opt.shiftwidth = 2
opt.background = dark
opt.syntax = "on"
g.mix_format_on_save = 1
