alias s:= switch

switch:
  nix run nix-darwin -- switch --flake ~/.run_commands/.config/darwin# 

nflake:
  nvim ~/.run_commands/.config/darwin/flake.nix

nhome:
  nvim ~/.run_commands/.config/darwin/home.nix
